### ISSUE TITLE
language code suggestion

### ISSUE THREAD

**Issue by lambone** [blitz-js/blitzjs.com-translation#6]
Hi
I am interested to help with the translation to Simplified Chinese.  But according to ISO 639-1,  2-letter is not good to differentiate the Simplified Chinese( used in Mainland China) and Traditional Chinese ( Used in Taiwan, Hong Kong, Macau, etc) 

May I suggest to use below 
- zh_CN | Chinese (China)
- zh_TW | Chinese (Taiwan)

https://developer.chrome.com/docs/webstore/i18n/

Regards

**Comment by JuanM04** [comment]
What do you think about `zh-hans` and `zh-hant`?

**Comment by flybayer** [comment]
> What do you think about `zh-hans` and `zh-hant`?

This is what Reactjs.org translations use

**Comment by lambone** [comment]
@flybayer yes you are right regarding Reactjs.org.  Previously, I was looking into the below tool 
https://docusaurus.io/docs/en/translation/#crowdin

**Comment by JuanM04** [comment]
We will use `zh-hans` and `zh-hant`
